// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // 임시로 웹 설정 사용 (개발 중)
        // 프로덕션에서는 FlutterFire CLI로 Android 앱을 등록해야 합니다
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBZqtkKTkYpa78Jq3-ZCVokYjjm5IqiIg',
    appId: '1:510898282975:web:8a8c9d97e18cf5d7f6646a',
    messagingSenderId: '510898282975',
    projectId: 'ssamdaeshin-d0ba7',
    authDomain: 'ssamdaeshin-d0ba7.firebaseapp.com',
    storageBucket: 'ssamdaeshin-d0ba7.firebasestorage.app',
    measurementId: 'G-W0M1F1LKMC',
  );

  // Android 설정 (임시로 웹 설정과 동일하게 사용)
  // 프로덕션에서는 FlutterFire CLI로 Android 앱을 등록하고 고유한 설정을 사용해야 합니다
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBZqtkKTkYpa78Jq3-ZCVokYjjm5IqiIg',
    appId: '1:510898282975:android:placeholder', // 실제 Android 앱 ID로 교체 필요
    messagingSenderId: '510898282975',
    projectId: 'ssamdaeshin-d0ba7',
    storageBucket: 'ssamdaeshin-d0ba7.firebasestorage.app',
  );
}
