"""add_encryption_hash_fields

Revision ID: 27d930263f9f
Revises: fa0aeef1c172
Create Date: 2025-11-11 17:21:07.734010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text, String


# revision identifiers, used by Alembic.
revision: str = '27d930263f9f'
down_revision: Union[str, None] = 'fa0aeef1c172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 해시 필드 추가 (String(64) - HMAC-SHA256 hex = 64 chars)
    # 먼저 nullable=True로 추가하고, 데이터 채운 후 NOT NULL로 변경
    op.add_column('students', sa.Column('name_hash', String(64), nullable=True))
    op.add_column('students', sa.Column('phone_hash', String(64), nullable=True))
    
    # 기존 데이터의 해시값 채우기 (Python에서 실행)
    # 이 부분은 마이그레이션 스크립트에서 처리하거나, 별도 스크립트로 실행
    # 여기서는 기본값을 설정하고, 애플리케이션 레벨에서 자동으로 채워짐
    
    # 암호화 필드 타입 변경 (VARCHAR -> TEXT, 암호화된 JSON 저장)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=Text(),
               existing_nullable=False)
    op.alter_column('students', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=Text(),
               existing_nullable=False)
    op.alter_column('students', 'parent_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=Text(),
               existing_nullable=True)
    op.drop_constraint('uniq_name_phone', 'students', type_='unique')
    
    # 해시 필드에 인덱스 생성 (nullable=True 상태에서)
    op.create_index(op.f('ix_students_name_hash'), 'students', ['name_hash'], unique=False)
    op.create_index(op.f('ix_students_phone_hash'), 'students', ['phone_hash'], unique=False)
    
    # 기존 데이터가 있으면 해시값을 채워야 함
    # 이 부분은 마이그레이션 후 별도 스크립트로 실행하거나,
    # 애플리케이션에서 자동으로 채워짐 (setup_hash_fields 이벤트 리스너)
    
    # 해시 필드를 NOT NULL로 변경 (기존 데이터가 없거나 모두 채워진 후)
    # 주의: 기존 데이터가 있으면 먼저 해시값을 채워야 함
    # op.alter_column('students', 'name_hash', nullable=False)
    # op.alter_column('students', 'phone_hash', nullable=False)
    
    # unique constraint는 해시값이 모두 채워진 후에 생성
    # op.create_unique_constraint('uniq_name_phone', 'students', ['name_hash', 'phone_hash'])
    # 해시 필드 추가
    op.add_column('teachers', sa.Column('phone_hash', String(64), nullable=True))
    op.add_column('teachers', sa.Column('email_hash', String(64), nullable=True))
    
    # 암호화 필드 타입 변경
    op.alter_column('teachers', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=Text(),
               existing_nullable=False)
    op.alter_column('teachers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=Text(),
               existing_nullable=False)
    op.alter_column('teachers', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=Text(),
               existing_nullable=True)
    op.alter_column('teachers', 'bank_name',
               existing_type=sa.VARCHAR(length=50),
               type_=Text(),
               existing_nullable=True)
    op.alter_column('teachers', 'account_number',
               existing_type=sa.VARCHAR(length=30),
               type_=Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_teachers_email_hash'), 'teachers', ['email_hash'], unique=False)
    op.create_index(op.f('ix_teachers_phone_hash'), 'teachers', ['phone_hash'], unique=False)
    
    # 주의: 기존 데이터가 있으면 해시값을 채운 후 NOT NULL로 변경해야 함
    # op.alter_column('teachers', 'phone_hash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_phone_hash'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email_hash'), table_name='teachers')
    op.alter_column('teachers', 'account_number',
               existing_type=Text(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('teachers', 'bank_name',
               existing_type=Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('teachers', 'email',
               existing_type=Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('teachers', 'phone',
               existing_type=Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('teachers', 'name',
               existing_type=Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('teachers', 'email_hash')
    op.drop_column('teachers', 'phone_hash')
    op.drop_index(op.f('ix_students_phone_hash'), table_name='students')
    op.drop_index(op.f('ix_students_name_hash'), table_name='students')
    op.drop_constraint('uniq_name_phone', 'students', type_='unique')
    op.create_unique_constraint('uniq_name_phone', 'students', ['name', 'phone'])
    op.alter_column('students', 'parent_phone',
               existing_type=Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('students', 'phone',
               existing_type=Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('students', 'name',
               existing_type=Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('students', 'phone_hash')
    op.drop_column('students', 'name_hash')
    # ### end Alembic commands ###
