"""add social auth to teachers

Revision ID: 4f50c43709a4
Revises: ec6023d8362b
Create Date: 2025-11-11 15:56:00.165892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f50c43709a4'
down_revision: Union[str, None] = 'ec6023d8362b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    provider_enum = sa.Enum('google', 'kakao', 'naver', 'apple', name='auth_provider')
    provider_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('teachers', sa.Column('provider', provider_enum, nullable=False))
    op.add_column('teachers', sa.Column('oauth_id', sa.String(length=191), nullable=False))
    op.create_unique_constraint('uniq_provider_oauth_id', 'teachers', ['provider', 'oauth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_provider_oauth_id', 'teachers', type_='unique')
    op.drop_column('teachers', 'oauth_id')
    op.drop_column('teachers', 'provider')
    provider_enum = sa.Enum('google', 'kakao', 'naver', 'apple', name='auth_provider')
    provider_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
