"""add email column to students

Revision ID: 6edde0daf5e7
Revises: fbeeb3b8c0c3
Create Date: 2025-11-11 08:50:20.659330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edde0daf5e7'
down_revision: Union[str, None] = 'fbeeb3b8c0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.String(length=120), nullable=True))
    op.alter_column('students', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('students', 'student_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('students', 'grade',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('students', 'guardian_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index('ix_students_user_id', table_name='students')
    op.create_index(op.f('ix_students_grade'), 'students', ['grade'], unique=False)
    op.create_index(op.f('ix_students_guardian_phone'), 'students', ['guardian_phone'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_student_phone'), 'students', ['student_phone'], unique=False)
    op.drop_column('students', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_students_student_phone'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_guardian_phone'), table_name='students')
    op.drop_index(op.f('ix_students_grade'), table_name='students')
    op.create_index('ix_students_user_id', 'students', ['user_id'], unique=False)
    op.alter_column('students', 'guardian_phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('students', 'grade',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('students', 'student_phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('students', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('students', 'email')
    # ### end Alembic commands ###
