"""add teacher_subjects and student_subjects tables

Revision ID: b46302f1bb76
Revises: 4f50c43709a4
Create Date: 2025-11-11 16:35:06.270597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46302f1bb76'
down_revision: Union[str, None] = '4f50c43709a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_subjects',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=False),
    sa.Column('lesson_day', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'teacher_id', 'subject')
    )
    op.create_table('teacher_subjects',
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'subject')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_subjects')
    op.drop_table('student_subjects')
    # ### end Alembic commands ###
