"""add_is_adult_to_students

Revision ID: cced1f6db171
Revises: 27d930263f9f
Create Date: 2025-11-12 10:56:33.579006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cced1f6db171'
down_revision: Union[str, None] = '27d930263f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # is_adult 컬럼 추가 (기본값: False)
    op.add_column('students', sa.Column('is_adult', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    
    # 기존 데이터의 NULL 해시 값 처리
    # name_hash나 phone_hash가 NULL인 경우 임시 값으로 채우기
    # (실제 해시값은 애플리케이션 레벨에서 자동으로 채워짐)
    connection = op.get_bind()
    
    # NULL인 name_hash를 임시로 채우기 (실제 해시값은 나중에 애플리케이션에서 업데이트)
    connection.execute(sa.text("""
        UPDATE students 
        SET name_hash = '0000000000000000000000000000000000000000000000000000000000000000'
        WHERE name_hash IS NULL
    """))
    
    # NULL인 phone_hash를 임시로 채우기
    connection.execute(sa.text("""
        UPDATE students 
        SET phone_hash = '0000000000000000000000000000000000000000000000000000000000000000'
        WHERE phone_hash IS NULL
    """))
    
    # 이제 NOT NULL 제약 조건 추가 가능
    op.alter_column('students', 'name_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('students', 'phone_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    
    # unique constraint는 해시값이 모두 채워진 후에 생성
    # 임시 값이 있으면 unique constraint 생성 실패할 수 있으므로 주의
    # 실제로는 애플리케이션에서 해시값을 업데이트한 후 unique constraint를 생성해야 함
    # 여기서는 일단 생성하지 않고, 나중에 별도 마이그레이션으로 처리
    # op.create_unique_constraint('uniq_name_phone', 'students', ['name_hash', 'phone_hash'])
    
    # teachers 테이블의 phone_hash도 동일하게 처리
    connection.execute(sa.text("""
        UPDATE teachers 
        SET phone_hash = '0000000000000000000000000000000000000000000000000000000000000000'
        WHERE phone_hash IS NULL
    """))
    
    op.alter_column('teachers', 'phone_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'phone_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # unique constraint는 upgrade에서 생성하지 않았으므로 drop도 하지 않음
    # op.drop_constraint('uniq_name_phone', 'students', type_='unique')
    op.alter_column('students', 'phone_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('students', 'name_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('students', 'is_adult')
    # ### end Alembic commands ###
