"""create schedules table

Revision ID: ec6023d8362b
Revises: f9bf3b4e2587
Create Date: 2025-11-11 15:48:06.632068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6023d8362b'
down_revision: Union[str, None] = 'f9bf3b4e2587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('schedule_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.Column('schedule_type', sa.Enum('lesson', 'available', 'vacation', 'personal', name='schedule_type'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), server_default='#3788D8', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('schedule_id'),
    sa.UniqueConstraint('teacher_id', 'lesson_date', 'start_time', name='uniq_teacher_date_time')
    )
    op.create_index('idx_date', 'schedules', ['lesson_date'], unique=False)
    op.create_index('idx_student', 'schedules', ['student_id'], unique=False)
    op.create_index('idx_teacher', 'schedules', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_schedules_lesson_date'), 'schedules', ['lesson_date'], unique=False)
    op.create_index(op.f('ix_schedules_student_id'), 'schedules', ['student_id'], unique=False)
    op.create_index(op.f('ix_schedules_teacher_id'), 'schedules', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_teacher_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_student_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_lesson_date'), table_name='schedules')
    op.drop_index('idx_teacher', table_name='schedules')
    op.drop_index('idx_student', table_name='schedules')
    op.drop_index('idx_date', table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
