"""drop address column from students

Revision ID: f1da785912bd
Revises: 758b40a42239
Create Date: 2025-11-11 15:26:53.927384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1da785912bd'
down_revision: Union[str, None] = '758b40a42239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
