"""create teachers table

Revision ID: f9bf3b4e2587
Revises: f1da785912bd
Create Date: 2025-11-11 15:33:16.342766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9bf3b4e2587'
down_revision: Union[str, None] = 'f1da785912bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('teacher_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=30), nullable=True),
    sa.Column('tax_type', sa.Enum('사업소득', '기타소득', '프리랜서', '미신고', name='teacher_tax_type'), server_default='사업소득', nullable=False),
    sa.Column('hourly_rate_min', sa.Integer(), nullable=True),
    sa.Column('hourly_rate_max', sa.Integer(), nullable=True),
    sa.Column('available_days', sa.String(length=100), nullable=True),
    sa.Column('available_time', sa.String(length=200), nullable=True),
    sa.Column('vacation_start', sa.Date(), nullable=True),
    sa.Column('vacation_end', sa.Date(), nullable=True),
    sa.Column('total_students', sa.Integer(), server_default='0', nullable=False),
    sa.Column('monthly_income', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), server_onupdate=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    # ### end Alembic commands ###
